"""Generate private wire constants and reference from semconv YAML."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import jsonschema
import yaml

ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    definition = yaml.safe_load((ROOT / "semconv/code_artifact.yaml").read_text())
    schema = json.loads((ROOT / "semconv/vendor/semconv.schema.json").read_text())
    jsonschema.validate(definition, schema)
    groups = definition["groups"]
    attrs = groups[0]["attributes"]
    ids = [a["id"] for a in attrs]
    assert len(ids) == len(set(ids)), "duplicate attribute IDs"
    code = ['"""Generated by scripts/generate_semconv.py; do not edit."""', ""]
    docs = [
        "# code_artifact wire attributes",
        "",
        "Generated from `code_artifact.yaml`. Experimental schema **0.1.0**.",
        "",
        "All nine attributes are required on recording spans; check arrays may be empty.",
        "See [the execution contract](../docs/adr/0006-first-release-contract.md) for validation and privacy rules.",
        "",
        "| Attribute | Type | Meaning |",
        "| --- | --- | --- |",
    ]
    for attr in attrs:
        assert attr["type"] in {"string", "string[]", "double[]"}
        name = attr["id"].removeprefix("code_artifact.").replace(".", "_").upper()
        code.append(f'{name} = "{attr["id"]}"')
        docs.append(f"| `{attr['id']}` | `{attr['type']}` | {attr['brief']} |")
    outputs = {
        ROOT / "src/melampus/_semconv.py": "\n".join(code) + "\n",
        ROOT / "semconv/README.md": "\n".join(docs) + "\n",
    }
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"stale generated file: {path.relative_to(ROOT)}")
        else:
            path.write_text(content)
    print("Semantic convention constants and reference are current.")


if __name__ == "__main__":
    main()
